### ISSUE TITLE
npm start  error   yield next;

### ISSUE THREAD

**Issue by zanjs** [jackhutu/jackblog-api-koa#1]
> gulp serve

[09:26:36] Using gulpfile E:\zan\www\koa\jackblog-api-koa\gulpfile.js
[09:26:36] Starting 'nodemon'...
[09:26:36] Finished 'nodemon' after 2.96 ms
[09:26:36] Starting 'serve'...
[09:26:36] Finished 'serve' after 8.02 μs
[09:26:36] [nodemon] 1.8.1
[09:26:36] [nodemon] to restart at any time, enter `rs`
[09:26:36] [nodemon] watching: E:\zan\www\koa\jackblog-api-koa\server/**/*
[09:26:36] [nodemon] starting `node server\app.js`
E:\zan\www\koa\jackblog-api-koa\server\config\seed.js:112
                        yield next;
                        ^^^^^

SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (E:\zan\www\koa\jackblog-api-koa\server\app.js:23:1
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
[09:26:37] [nodemon] app crashed - waiting for file changes before starting..

**Comment by jackhutu** [comment]
是seed.js 有问题,已经修复了.
