### ISSUE TITLE
windows下运行报错了

### ISSUE THREAD

**Issue by mlyknown** [jackhutu/jackblog-api-koa#2]
$ gulp serve
[00:06:45] Using gulpfile E:\MyProject\bishe\boke\jackblog-api-koa\gulpfile.js
[00:06:45] Starting 'nodemon'...
[00:06:45] Finished 'nodemon' after 2.27 ms
[00:06:45] Starting 'serve'...
[00:06:45] Finished 'serve' after 7.8 μs
[00:06:45] [nodemon] 1.9.1
[00:06:45] [nodemon] to restart at any time, enter `rs`
[00:06:45] [nodemon] watching: E:\MyProject\bishe\boke\jackblog-api-koa\server/**/*
[00:06:45] [nodemon] starting `node --harmony server\app.js`
module.js:327
    throw err;
    ^

Error: Cannot find module '../build/Release/hcaptha.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\MyProject\bishe\boke\jackblog-api-koa\node_modules\.npminstall\ccap\0.6.4\ccap\lib\hcap.js:4:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\MyProject\bishe\boke\jackblog-api-koa\node_modules\.npminstall\ccap\0.6.4\ccap\index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
[00:06:46] [nodemon] app crashed - waiting for file changes before starting...

**Comment by jackhutu** [comment]
貌似ccap这个库未安装好, 它需要C++编译环境, ```npm i ccap``` 重新安装试试是否能正确安装? 另node和npm 版本是多少?

**Comment by mlyknown** [comment]
node v4.4.2  , npm v2.15...... 我用cnpm安装的，这个好像是已经编译好的。。

**Comment by mlyknown** [comment]
从github上面直接下载 ccap 替换就解决的。但是出现新的错误了

Koa server listening on 9000, in development mode
  <-- GET /article/getIndexImage
  <-- GET /tags/getFrontTagList
  <-- GET /article/getFrontArticleList?currentPage=1&itemsPerPage=10&sortName=publish_time&tagId=
E:\MyProject\bishe\boke\jackblog-api-koa\node_modules\qiniu\qiniu\rpc.js:57
    onresp(rerr, result, res);
    ^

TypeError: onresp is not a function
    at E:\MyProject\bishe\boke\jackblog-api-koa\node_modules\qiniu\qiniu\rpc.js:57:5
    at done (E:\MyProject\bishe\boke\jackblog-api-koa\node_modules\qiniu\node_modules\urllib\lib\urllib.js:193:5)
    at IncomingMessage.<anonymous> (E:\MyProject\bishe\boke\jackblog-api-koa\node_modules\qiniu\node_modules\urllib\lib\urllib.js:304:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

七牛一定要自己配置config吗？
验证码哪里也还是没出现。
![qq 20160428164834](https://cloud.githubusercontent.com/assets/12880984/14880395/266863da-0d61-11e6-9e30-8ac769fe91f6.png)

**Comment by jackhutu** [comment]
七牛不配置, 也可以跑.  你在浏览器单独访问 getIndexImage 这个API 看看.

**Comment by jackhutu** [comment]
七牛在没配置时, 在第二次请求首页图片时, 确实有错误, 已经修复. 另外针对windows环境专门测试了一下. 有一些注意事项可以看看. [https://github.com/jackhutu/jackblog-api-koa#windows](https://github.com/jackhutu/jackblog-api-koa#windows)
